name: build docs

on:
  push:
    branches:
      - main
    paths:
      - 'src/docs/**'
  pull_request:
    paths:
      - 'src/docs/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: src/docs

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.125.1'
          extended: true

      - name: Build docs
        working-directory: src/docs
        run: |
          hugo mod npm pack
          npm install
          hugo --verbose
